//NetBeans versao 23
//Livia Almeida Rosa
//Compilar usando o triangulo verde pois alt f6 abre Test Result
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.util.logging.Logger;

public class FormPrincipal extends javax.swing.JFrame {
    
   private static final Logger logger = Logger.getLogger(FormPrincipal.class.getName());
   private static FormPrincipal formPrincipalUnico;
    
    private FormPrincipal() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    public static FormPrincipal getFormPrincipal() {
        if (formPrincipalUnico == null) {
            formPrincipalUnico = new FormPrincipal();
        }
        return formPrincipalUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloFormpRINC = new javax.swing.JLabel();
        MenuPrincipal = new javax.swing.JMenuBar();
        RelatorioMenu = new javax.swing.JMenu();
        RelGeral = new javax.swing.JMenuItem();
        btSairFormPrinc2 = new javax.swing.JMenuItem();
        CadastroPrinMenu = new javax.swing.JMenu();
        CadGeFormPrinc = new javax.swing.JMenu();
        CadCliente = new javax.swing.JMenuItem();
        CadFunc = new javax.swing.JMenuItem();
        CadGerente = new javax.swing.JMenuItem();
        CadVeiculo = new javax.swing.JMenuItem();
        CadRegistroEstacionamento = new javax.swing.JMenuItem();
        CadSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tituloFormpRINC.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        tituloFormpRINC.setText("Formulário Principal Livia Rosa");

        RelatorioMenu.setText("Relatório");

        RelGeral.setText("Relatorio Geral...");
        RelGeral.addActionListener(this::RelGeralActionPerformed);
        RelatorioMenu.add(RelGeral);

        btSairFormPrinc2.setText("Sair...");
        btSairFormPrinc2.addActionListener(this::btSairFormPrinc2ActionPerformed);
        RelatorioMenu.add(btSairFormPrinc2);

        MenuPrincipal.add(RelatorioMenu);

        CadastroPrinMenu.setText("Cadastro");

        CadGeFormPrinc.setText("Cadastros:");

        CadCliente.setText("Cliente");
        CadCliente.addActionListener(this::CadClienteActionPerformed);
        CadGeFormPrinc.add(CadCliente);

        CadFunc.setText("Funcionário");
        CadFunc.addActionListener(this::CadFuncActionPerformed);
        CadGeFormPrinc.add(CadFunc);

        CadGerente.setText("Gerente");
        CadGerente.addActionListener(this::CadGerenteActionPerformed);
        CadGeFormPrinc.add(CadGerente);

        CadVeiculo.setText("Veiculo");
        CadVeiculo.addActionListener(this::CadVeiculoActionPerformed);
        CadGeFormPrinc.add(CadVeiculo);

        CadRegistroEstacionamento.setText("Registrar Estacionamento");
        CadRegistroEstacionamento.addActionListener(this::CadRegistroEstacionamentoActionPerformed);
        CadGeFormPrinc.add(CadRegistroEstacionamento);

        CadSair.setText("Sair...");
        CadSair.addActionListener(this::CadSairActionPerformed);
        CadGeFormPrinc.add(CadSair);

        CadastroPrinMenu.add(CadGeFormPrinc);

        MenuPrincipal.add(CadastroPrinMenu);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tituloFormpRINC)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(tituloFormpRINC)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CadSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadSairActionPerformed
        sair();
    }//GEN-LAST:event_CadSairActionPerformed

    private void CadRegistroEstacionamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadRegistroEstacionamentoActionPerformed
        FormCadRegEst.getFormCadRegEst().setVisible(true);
    }//GEN-LAST:event_CadRegistroEstacionamentoActionPerformed

    private void CadVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadVeiculoActionPerformed
        FormCadVeiculo.getFormCadVeiculoUnico().setVisible(true);
    }//GEN-LAST:event_CadVeiculoActionPerformed

    private void CadGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadGerenteActionPerformed
        FormCadGerente.getFormCadGerente().setVisible(true);
    }//GEN-LAST:event_CadGerenteActionPerformed

    private void CadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadFuncActionPerformed
        FormCadFuncionario.getFormCadFuncionario().setVisible(true);
    }//GEN-LAST:event_CadFuncActionPerformed

    private void CadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadClienteActionPerformed
        FormCadastroCliente.getFormCadastroCliente().setVisible(true);
    }//GEN-LAST:event_CadClienteActionPerformed

    private void RelGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelGeralActionPerformed
       FormRelatorioGeral.getFormRelatorioGeral().setVisible(true);
    }//GEN-LAST:event_RelGeralActionPerformed

    private void btSairFormPrinc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairFormPrinc2ActionPerformed
        sair();
    }//GEN-LAST:event_btSairFormPrinc2ActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(
            this, // Usa 'this'
            "Deseja realmente sair?",
            "Saida",
            JOptionPane.YES_NO_OPTION
        );
        if(resp == 0){
            dispose(); 
        }
    }
    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
   
    

    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            
            FormPrincipal.getFormPrincipal().setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadCliente;
    private javax.swing.JMenuItem CadFunc;
    private javax.swing.JMenu CadGeFormPrinc;
    private javax.swing.JMenuItem CadGerente;
    private javax.swing.JMenuItem CadRegistroEstacionamento;
    private javax.swing.JMenuItem CadSair;
    private javax.swing.JMenuItem CadVeiculo;
    private javax.swing.JMenu CadastroPrinMenu;
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JMenuItem RelGeral;
    private javax.swing.JMenu RelatorioMenu;
    private javax.swing.JMenuItem btSairFormPrinc2;
    private javax.swing.JLabel tituloFormpRINC;
    // End of variables declaration//GEN-END:variables
}
