//Livia Almeida Rosa
import javax.swing.JOptionPane;
public class FormCadVeiculo extends javax.swing.JFrame {

     private static FormCadVeiculo FormCadVeiculoUnico;
     
     private BDPrincipal bd = BDPrincipal.getBDPrincipal();
     private Veiculo VeiculoTemp = new Veiculo();
    
    private FormCadVeiculo() {
        initComponents();
    }

    
//MÉTODO SINGLETON
public static FormCadVeiculo getFormCadVeiculoUnico(){
    if(FormCadVeiculoUnico == null){
        FormCadVeiculoUnico = new FormCadVeiculo();
    } 
    return FormCadVeiculoUnico; 
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtPlaca = new javax.swing.JLabel();
        rtModelo = new javax.swing.JLabel();
        rtCor = new javax.swing.JLabel();
        TextPlaca = new javax.swing.JTextField();
        TextModelo = new javax.swing.JTextField();
        TextCor = new javax.swing.JTextField();
        btInsVeiculo = new javax.swing.JButton();
        btAltVeiculo = new javax.swing.JButton();
        btDeletVeiculo = new javax.swing.JButton();
        btConsVeiculo = new javax.swing.JButton();
        btLimparVeiculo = new javax.swing.JButton();
        btSairVeiculo = new javax.swing.JButton();
        TituloVeiculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtPlaca.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtPlaca.setText("PLACA");

        rtModelo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtModelo.setText("MODELO");

        rtCor.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtCor.setText("COR");

        TextCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorActionPerformed(evt);
            }
        });

        btInsVeiculo.setText("Inserir");
        btInsVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsVeiculoActionPerformed(evt);
            }
        });

        btAltVeiculo.setText("Alterar");
        btAltVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltVeiculoActionPerformed(evt);
            }
        });

        btDeletVeiculo.setText("Deletar");
        btDeletVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletVeiculoActionPerformed(evt);
            }
        });

        btConsVeiculo.setText("Consultar Placa");
        btConsVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsVeiculoActionPerformed(evt);
            }
        });

        btLimparVeiculo.setText("Limpar");
        btLimparVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparVeiculoActionPerformed(evt);
            }
        });

        btSairVeiculo.setText("Sair");
        btSairVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairVeiculoActionPerformed(evt);
            }
        });

        TituloVeiculo.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        TituloVeiculo.setText("Cadastro Veiculo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLimparVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSairVeiculo)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(rtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rtModelo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rtPlaca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextPlaca)
                            .addComponent(TextModelo)
                            .addComponent(TextCor, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btInsVeiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAltVeiculo)
                        .addGap(18, 18, 18)
                        .addComponent(btDeletVeiculo)
                        .addGap(18, 18, 18)
                        .addComponent(btConsVeiculo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(TituloVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtPlaca)
                    .addComponent(TextPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtModelo)
                    .addComponent(TextModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtCor))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsVeiculo)
                    .addComponent(btAltVeiculo)
                    .addComponent(btDeletVeiculo)
                    .addComponent(btConsVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(TituloVeiculo)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparVeiculo)
                    .addComponent(btSairVeiculo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorActionPerformed

    private void btInsVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsVeiculoActionPerformed
        insVeiculo();
    }//GEN-LAST:event_btInsVeiculoActionPerformed

    private void btAltVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltVeiculoActionPerformed
        altVeiculoPlaca();
    }//GEN-LAST:event_btAltVeiculoActionPerformed

    private void btDeletVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletVeiculoActionPerformed
        apagVeiculoPlaca();
    }//GEN-LAST:event_btDeletVeiculoActionPerformed

    private void btConsVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsVeiculoActionPerformed
        consVeiculoPlaca();
    }//GEN-LAST:event_btConsVeiculoActionPerformed

    private void btLimparVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparVeiculoActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparVeiculoActionPerformed

    private void btSairVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairVeiculoActionPerformed
        sairFormulario();
    }//GEN-LAST:event_btSairVeiculoActionPerformed
private void limparCampos() {
    TextPlaca.setText("");
    TextModelo.setText("");
    TextCor.setText("");
    TextPlaca.requestFocus();
}

public void apagVeiculoPlaca(){
    Veiculo veiculoTemp = new Veiculo();
    veiculoTemp.setPlaca(TextPlaca.getText()); 
    Veiculo veiTemp = bd.delVeiculoPlaca(veiculoTemp);
    
    if(veiTemp == null){ 
        JOptionPane.showMessageDialog(
            null,
            "Veículo deletado com sucesso!",
            "Deleção de Veículo",
            JOptionPane.INFORMATION_MESSAGE
        );
        limparCampos();
    }
    else{ 
        JOptionPane.showMessageDialog(
            null,
            "Não existe Veículo com esta Placa!",
            "Deleção de Veículo",
            JOptionPane.ERROR_MESSAGE
        );
        TextPlaca.setText("");
        TextPlaca.requestFocus();
    }
}
    
public void altVeiculoPlaca(){
    Veiculo veiculoTemp = new Veiculo();
    veiculoTemp.setPlaca(TextPlaca.getText());
    veiculoTemp = bd.atualizaVeiculoPlaca(veiculoTemp);
    
    if(veiculoTemp != null){
        
        TextPlaca.setText(veiculoTemp.getPlaca());
        TextModelo.setText(veiculoTemp.getModelo());
        TextCor.setText(veiculoTemp.getCor());
        
        JOptionPane.showMessageDialog(
            null,
            "Veículo atualizado com sucesso! Confira os dados",
            "Alteração de Veículo",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    else{
        JOptionPane.showMessageDialog(
            null,
            "Não existe Veículo com esta Placa!",
            "Alteração de Veículo",
            JOptionPane.ERROR_MESSAGE
        );
    TextPlaca.setText("");
    TextPlaca.requestFocus();
    }
}
    
public void consVeiculoPlaca(){
    Veiculo veiculoTemp = new Veiculo();
    veiculoTemp.setPlaca(TextPlaca.getText());
    veiculoTemp = bd.consVeiculoPlaca(veiculoTemp);
    
    if(veiculoTemp != null){
        TextPlaca.setText(veiculoTemp.getPlaca());
        TextModelo.setText(veiculoTemp.getModelo());
        TextCor.setText(veiculoTemp.getCor());
        
        JOptionPane.showMessageDialog(
            null,
            "Veículo encontrado com sucesso! Confira os dados",
            "Consulta de Veículo",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    else{
        JOptionPane.showMessageDialog(
            null,
            "Não existe Veículo com esta Placa!",
            "Consulta de Veículo",
            JOptionPane.ERROR_MESSAGE
        );
    TextPlaca.setText("");
    TextPlaca.requestFocus();
    }
}
    
public void insVeiculo(){
    Veiculo veiculoTemp = new Veiculo();
    veiculoTemp.setPlaca(TextPlaca.getText());
    veiculoTemp.setModelo(TextModelo.getText());
    veiculoTemp.setCor(TextCor.getText());

    Veiculo veiInserido = bd.insVeiculo(veiculoTemp);

    if(veiInserido != null){
        JOptionPane.showMessageDialog(
            null,
            "Veículo inserido com sucesso!",
            "Inserção de Veículo",
            JOptionPane.INFORMATION_MESSAGE
        );
        limparCampos();
    }
    else{
        JOptionPane.showMessageDialog(
            null,
            "Já existe um Veículo com esta Placa!",
            "Inserção de Veículo",
            JOptionPane.ERROR_MESSAGE
        );
        TextPlaca.setText("");
        TextPlaca.requestFocus();
     }
    }

    

public void sairFormulario(){
    int resp = JOptionPane.showConfirmDialog(
        null,    
        "Realmente deseja sair?",
        "Confirmação de Saída",
        JOptionPane.YES_NO_OPTION
    );
    
    if(resp == 0){    
        dispose();    
    }
}
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextCor;
    private javax.swing.JTextField TextModelo;
    private javax.swing.JTextField TextPlaca;
    private javax.swing.JLabel TituloVeiculo;
    private javax.swing.JButton btAltVeiculo;
    private javax.swing.JButton btConsVeiculo;
    private javax.swing.JButton btDeletVeiculo;
    private javax.swing.JButton btInsVeiculo;
    private javax.swing.JButton btLimparVeiculo;
    private javax.swing.JButton btSairVeiculo;
    private javax.swing.JLabel rtCor;
    private javax.swing.JLabel rtModelo;
    private javax.swing.JLabel rtPlaca;
    // End of variables declaration//GEN-END:variables
}
