//Livia Almeida Rosa
import javax.swing.JOptionPane;
public class FormCadGerente extends javax.swing.JFrame {

    
     private static FormCadGerente FormCadGerenteUnico;
    
      private BDPrincipal bd = BDPrincipal.getBDPrincipal();
      private Gerente GerenteTemp = new Gerente();
     
    private FormCadGerente() {
        initComponents();
    }
    
    //MÉTODO SINGLETON
public static  FormCadGerente getFormCadGerente(){
    if(FormCadGerenteUnico == null){
        FormCadGerenteUnico = new FormCadGerente();
    } 
    return FormCadGerenteUnico; 
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtNome = new javax.swing.JLabel();
        rtCpf = new javax.swing.JLabel();
        rtId = new javax.swing.JLabel();
        rtSetor = new javax.swing.JLabel();
        TextNome3 = new javax.swing.JTextField();
        TextCpf3 = new javax.swing.JTextField();
        TextId3 = new javax.swing.JTextField();
        TextSetor3 = new javax.swing.JTextField();
        btInsGerente = new javax.swing.JButton();
        btAltGerente = new javax.swing.JButton();
        btDeletGerente = new javax.swing.JButton();
        btConsGerente = new javax.swing.JButton();
        btLimparGerente = new javax.swing.JButton();
        btSairGerente = new javax.swing.JButton();
        Titulogerente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtNome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtNome.setText("NOME");

        rtCpf.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtCpf.setText("CPF");

        rtId.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtId.setText("ID");

        rtSetor.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtSetor.setText("SETOR");

        TextId3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextId3ActionPerformed(evt);
            }
        });

        btInsGerente.setText("Inserir");
        btInsGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsGerenteActionPerformed(evt);
            }
        });

        btAltGerente.setText("Alterar");
        btAltGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltGerenteActionPerformed(evt);
            }
        });

        btDeletGerente.setText("Deletar");
        btDeletGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeletGerenteActionPerformed(evt);
            }
        });

        btConsGerente.setText("Consultar Cpf");
        btConsGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsGerenteActionPerformed(evt);
            }
        });

        btLimparGerente.setText("Limpar");
        btLimparGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparGerenteActionPerformed(evt);
            }
        });

        btSairGerente.setText("Sair");
        btSairGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairGerenteActionPerformed(evt);
            }
        });

        Titulogerente.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        Titulogerente.setText("Cadastro Gerente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLimparGerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSairGerente)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextNome3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtSetor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextSetor3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(rtId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextId3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(rtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextCpf3, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Titulogerente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btInsGerente)
                                .addGap(18, 18, 18)
                                .addComponent(btAltGerente)))
                        .addGap(18, 18, 18)
                        .addComponent(btDeletGerente)
                        .addGap(18, 18, 18)
                        .addComponent(btConsGerente)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(TextNome3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(TextCpf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtId)
                    .addComponent(TextId3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtSetor)
                    .addComponent(TextSetor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsGerente)
                    .addComponent(btAltGerente)
                    .addComponent(btDeletGerente)
                    .addComponent(btConsGerente))
                .addGap(18, 18, 18)
                .addComponent(Titulogerente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparGerente)
                    .addComponent(btSairGerente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextId3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextId3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextId3ActionPerformed

    private void btInsGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsGerenteActionPerformed
        insGerente();
    }//GEN-LAST:event_btInsGerenteActionPerformed

    private void btAltGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltGerenteActionPerformed
        altGerenteCpf();
    }//GEN-LAST:event_btAltGerenteActionPerformed

    private void btDeletGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletGerenteActionPerformed
       apagGerenteCpf();
    }//GEN-LAST:event_btDeletGerenteActionPerformed

    private void btConsGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsGerenteActionPerformed
      consGerenteCpf();
    }//GEN-LAST:event_btConsGerenteActionPerformed

    private void btLimparGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparGerenteActionPerformed
       limparCampos();
    }//GEN-LAST:event_btLimparGerenteActionPerformed

    private void btSairGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairGerenteActionPerformed
        sairFormulario();
    }//GEN-LAST:event_btSairGerenteActionPerformed
private void limparCampos() {
    TextCpf3.setText("");
    TextNome3.setText(""); 
    TextSetor3.setText(""); 
    TextId3.setText(""); 
    TextCpf3.requestFocus();
}

public void apagGerenteCpf(){
    Gerente gerenteTemp = new Gerente();
    gerenteTemp.setCpf(Integer.parseInt(TextCpf3.getText())); 
    
    Gerente gerTemp = bd.delGerenteCpf(gerenteTemp);
    
    if(gerTemp == null){ 
        JOptionPane.showMessageDialog(
            null,
            "Gerente deletado com sucesso!",
            "Deleção de Gerente",
            JOptionPane.INFORMATION_MESSAGE
        );
        limparCampos();
    }
    else{ 
        JOptionPane.showMessageDialog(
            null,
            "Não existe Gerente com este CPF!",
            "Deleção de Gerente",
            JOptionPane.ERROR_MESSAGE
        );
        TextCpf3.setText("");
        TextCpf3.requestFocus();
    }
}

public void altGerenteCpf(){
    Gerente gerenteTemp = new Gerente();
        gerenteTemp.setCpf(Integer.parseInt(TextCpf3.getText()));
        gerenteTemp = bd.atualizaGerenteCpf(gerenteTemp); 
        if(gerenteTemp != null){

            TextCpf3.setText(Integer.toString(gerenteTemp.getCpf()));
            TextNome3.setText(gerenteTemp.getNome());

            JOptionPane.showMessageDialog(
                null,
                "Gerente atualizado com sucesso! Confira os dados",
                "Alteração de Gerente",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Gerente com este CPF!",
                "Alteração de Gerente",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf3.setText("");
            TextCpf3.requestFocus();
        }
    } 

public void consGerenteCpf(){
    Gerente gerenteTemp = new Gerente();
        gerenteTemp.setCpf(Integer.parseInt(TextCpf3.getText()));
        
        Gerente gerTemp = bd.consGerenteCpf(gerenteTemp);
        
        if(gerTemp != null){
            TextCpf3.setText(Integer.toString(gerTemp.getCpf()));
            TextNome3.setText(gerTemp.getNome());
            TextSetor3.setText(gerTemp.getSetor()); 
            TextId3.setText(String.valueOf(gerTemp.getIdGerente())); 
            Object nomeReflexivo = BDPrincipal.buscarNomeReflexivo(gerTemp); // //Reflexividade
            JOptionPane.showMessageDialog(
                null,
                "Gerente encontrado (Reflexivo: " + nomeReflexivo + ")! Confira os dados",
                "Consulta de Gerente",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Gerente com este CPF!",
                "Consulta de Gerente",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf3.setText("");
            TextCpf3.requestFocus();
        }
    } 


public void insGerente(){
    Gerente gerenteTemp = new Gerente();

    try{
        gerenteTemp.setCpf(Integer.parseInt(TextCpf3.getText()));
        gerenteTemp.setNome(TextNome3.getText());
        gerenteTemp.setSetor(TextSetor3.getText());
        gerenteTemp.setIdGerente(Integer.parseInt(TextId3.getText()));
        
        Gerente gerInserido = bd.insGerente(gerenteTemp);
        
        if(gerInserido != null){
            JOptionPane.showMessageDialog(
                null,
                "Gerente inserido com sucesso!",
                "Inserção de Gerente",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "ERRO: Inserção não realizada. Verifique se o Gerente está cadastrado como FUNCIONÁRIO e se não existe outro Gerente com este CPF.",
                "Erro de Inserção",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf3.setText("");
            TextCpf3.requestFocus();
        }
    }
    catch(NumberFormatException nfe){	
        JOptionPane.showMessageDialog(
            null,
            "O CPF e ID devem ser números inteiros",
            "Erro de Formato",
            JOptionPane.ERROR_MESSAGE
        );
        TextCpf3.setText("");
        TextCpf3.requestFocus();	
    }
}

public void sairFormulario(){
    int resp = JOptionPane.showConfirmDialog(
        this,	
        "Realmente deseja sair?",
        "Confirmação de Saída",
        JOptionPane.YES_NO_OPTION
    );
    
    if(resp == 0){	
        dispose();	
    }
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextCpf3;
    private javax.swing.JTextField TextId3;
    private javax.swing.JTextField TextNome3;
    private javax.swing.JTextField TextSetor3;
    private javax.swing.JLabel Titulogerente;
    private javax.swing.JButton btAltGerente;
    private javax.swing.JButton btConsGerente;
    private javax.swing.JButton btDeletGerente;
    private javax.swing.JButton btInsGerente;
    private javax.swing.JButton btLimparGerente;
    private javax.swing.JButton btSairGerente;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSetor;
    // End of variables declaration//GEN-END:variables
}
