//Livia Almeida Rosa
import javax.swing.JOptionPane;
public class FormCadRegEst extends javax.swing.JFrame {

   private static FormCadRegEst FormCadRegEstUnico; 
   
   private BDPrincipal bd = BDPrincipal.getBDPrincipal();
    private RegistroEstacionamento RegistroTemp = new RegistroEstacionamento();
    
    private FormCadRegEst() {
        initComponents();
    }
    
    //MÉTODO SINGLETON
public static FormCadRegEst getFormCadRegEst(){
    if(FormCadRegEstUnico == null){
        FormCadRegEstUnico = new FormCadRegEst();
    } 
    
    return FormCadRegEstUnico; 

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtCliente = new javax.swing.JLabel();
        rtVeiculoPlaca = new javax.swing.JLabel();
        rtIdFunc = new javax.swing.JLabel();
        insEntradaReg = new javax.swing.JButton();
        ConsPlacaReg = new javax.swing.JButton();
        RegRegSaida = new javax.swing.JButton();
        delReg = new javax.swing.JButton();
        TextCliente = new javax.swing.JTextField();
        TextVeiculo2 = new javax.swing.JTextField();
        TextCpfFunc = new javax.swing.JTextField();
        btLimparReg = new javax.swing.JButton();
        btSairReg = new javax.swing.JButton();
        TituloRegEst = new javax.swing.JLabel();
        btRelatGeralReg = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtCliente.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        rtCliente.setText("Cpf Cliente");

        rtVeiculoPlaca.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        rtVeiculoPlaca.setText("Veiculo Placa");

        rtIdFunc.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        rtIdFunc.setText("Cpf Funcionario");

        insEntradaReg.setText("Inserir Entrada");
        insEntradaReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insEntradaRegActionPerformed(evt);
            }
        });

        ConsPlacaReg.setText("Consultar Placa");
        ConsPlacaReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsPlacaRegActionPerformed(evt);
            }
        });

        RegRegSaida.setText("Registrar Saida");
        RegRegSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegRegSaidaActionPerformed(evt);
            }
        });

        delReg.setText("Deletar");
        delReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delRegActionPerformed(evt);
            }
        });

        btLimparReg.setText("Limpar");
        btLimparReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparRegActionPerformed(evt);
            }
        });

        btSairReg.setText("Sair...");
        btSairReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairRegActionPerformed(evt);
            }
        });

        TituloRegEst.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        TituloRegEst.setText("Cadastro Registro Estacionamento");

        btRelatGeralReg.setText("Relatorio Geral");
        btRelatGeralReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatGeralRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtIdFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rtCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rtVeiculoPlaca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TextVeiculo2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addComponent(TextCliente)
                            .addComponent(TextCpfFunc)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloRegEst))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(insEntradaReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RegRegSaida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delReg)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsPlacaReg)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btRelatGeralReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLimparReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btSairReg)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCliente)
                    .addComponent(TextCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtVeiculoPlaca)
                    .addComponent(TextVeiculo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtIdFunc)
                    .addComponent(TextCpfFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insEntradaReg)
                    .addComponent(RegRegSaida)
                    .addComponent(delReg)
                    .addComponent(ConsPlacaReg))
                .addGap(26, 26, 26)
                .addComponent(TituloRegEst)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparReg)
                    .addComponent(btSairReg)
                    .addComponent(btRelatGeralReg))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insEntradaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insEntradaRegActionPerformed
        registrarEntrada();
    }//GEN-LAST:event_insEntradaRegActionPerformed

    private void RegRegSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegRegSaidaActionPerformed
        registrarSaida();
    }//GEN-LAST:event_RegRegSaidaActionPerformed

    private void delRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delRegActionPerformed
        apagRegistro();
    }//GEN-LAST:event_delRegActionPerformed

    private void ConsPlacaRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsPlacaRegActionPerformed
        consRegistroAtivoPlaca();
    }//GEN-LAST:event_ConsPlacaRegActionPerformed

    private void btSairRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairRegActionPerformed
       sairFormulario();
    }//GEN-LAST:event_btSairRegActionPerformed

    private void btLimparRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparRegActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparRegActionPerformed

    private void btRelatGeralRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatGeralRegActionPerformed
        FormRelatorioGeral.getFormRelatorioGeral().setVisible(true);
    }//GEN-LAST:event_btRelatGeralRegActionPerformed
private void limparCampos() {
    TextCliente.setText("");
    TextVeiculo2.setText("");
    TextCpfFunc.setText("");
    TextVeiculo2.requestFocus();
}

public void apagRegistro(){
    try {
        String placa = TextVeiculo2.getText();
        RegistroEstacionamento regTemp = bd.consRegistroAtivoPlaca(placa);
        
        if(regTemp != null){
            bd.delRegistro(regTemp); 
            
            JOptionPane.showMessageDialog(
                null,
                "Registro deletado com sucesso!",
                "Deleção de Registro",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Registro Ativo com esta Placa!",
                "Deleção de Registro",
                JOptionPane.ERROR_MESSAGE
            );
            TextVeiculo2.setText("");
            TextVeiculo2.requestFocus();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "ERRO: Placa inválida ou ausente.", "Erro Geral", JOptionPane.ERROR_MESSAGE);
    }
}

public void registrarSaida(){
    try {
        String placa = TextVeiculo2.getText();
        RegistroEstacionamento regSaida = bd.registrarSaida(placa);
        
        if(regSaida != null){
            double valor = regSaida.calcularValor(); 
            long horas = java.time.Duration.between(regSaida.getHoraEntrada(), regSaida.getHoraSaida()).toHours();
            if (horas == 0) horas = 1; 
            
            JOptionPane.showMessageDialog(
                null,
                "SAÍDA REGISTRADA. Valor Fixo: R$ " + String.format("%.2f", valor),
                "Saída e Pagamento",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Registro Ativo para esta Placa!",
                "Saída",
                JOptionPane.ERROR_MESSAGE
            );
            TextVeiculo2.setText("");
            TextVeiculo2.requestFocus();
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "ERRO: Falha ao processar saída: " + ex.getMessage(), "Erro Geral", JOptionPane.ERROR_MESSAGE);
    }
}

public void consRegistroAtivoPlaca(){
    try {
        String placa = TextVeiculo2.getText();
        RegistroEstacionamento regTemp = bd.consRegistroAtivoPlaca(placa);

        if(regTemp != null){
            TextCliente.setText(String.valueOf(regTemp.getCliente().getCpf()));
            TextCpfFunc.setText(String.valueOf(regTemp.getFuncionario().getIdFuncionario()));
            TextVeiculo2.setText(regTemp.getVeiculo().getPlaca());
            
            JOptionPane.showMessageDialog(
                null,
                "Registro Ativo encontrado! Cliente: " + regTemp.getCliente().getNome() + "\nEntrada: " + regTemp.getHoraEntrada(),
                "Consulta de Registro",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos(); 
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Registro Ativo para esta Placa!",
                "Consulta de Registro",
                JOptionPane.ERROR_MESSAGE
            );
            TextVeiculo2.setText("");
            TextVeiculo2.requestFocus();
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, "ERRO: Placa inválida ou ausente.", "Erro Geral", JOptionPane.ERROR_MESSAGE);
    }
}
    
public void registrarEntrada(){
    RegistroEstacionamento r = new RegistroEstacionamento();
    Cliente c = new Cliente();
    Funcionario f = new Funcionario();
    Veiculo v = new Veiculo();
    
    try{
        c.setCpf(Integer.parseInt(TextCliente.getText()));
        f.setCpf(Integer.parseInt(TextCpfFunc.getText()));
        v.setPlaca(TextVeiculo2.getText());

        Cliente clienteBuscado = bd.consClienteCpf(c);
        Funcionario funcBuscado = bd.consFuncionarioCpf(f);
        Veiculo veiculoBuscado = bd.consVeiculoPlaca(v);
        
        if (clienteBuscado == null || funcBuscado == null || veiculoBuscado == null) {
             JOptionPane.showMessageDialog(null, "ERRO: Cliente, Funcionário ou Veículo não cadastrado(s).", "Dados Ausentes", JOptionPane.ERROR_MESSAGE);
             return;
        }
        
        r.setCliente(clienteBuscado);
        r.setFuncionario(funcBuscado);
        r.setVeiculo(veiculoBuscado);
        r.setHoraEntrada();
        
        RegistroEstacionamento regInserido = bd.insRegistro(r);

        if(regInserido != null){
            JOptionPane.showMessageDialog(
                null,
                "Entrada registrada com sucesso!",
                "Inserção de Registro",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Já existe um Registro Ativo para esta Placa!",
                "Inserção de Registro",
                JOptionPane.ERROR_MESSAGE
            );
            TextVeiculo2.requestFocus();
        }
    }
    catch(NumberFormatException nfe){
        JOptionPane.showMessageDialog(
            null,
            "O CPF e ID do Funcionário devem ser números inteiros",
            "Erro de Formato",
            JOptionPane.ERROR_MESSAGE
        );
        TextVeiculo2.requestFocus();
    }
}

public void sairFormulario(){
    int resp = JOptionPane.showConfirmDialog(
        null, 
        "Realmente deseja sair?",
        "Confirmação de Saída",
        JOptionPane.YES_NO_OPTION
    );
   
    if(resp == 0){ 
        dispose(); 
    }
}


    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConsPlacaReg;
    private javax.swing.JButton RegRegSaida;
    private javax.swing.JTextField TextCliente;
    private javax.swing.JTextField TextCpfFunc;
    private javax.swing.JTextField TextVeiculo2;
    private javax.swing.JLabel TituloRegEst;
    private javax.swing.JButton btLimparReg;
    private javax.swing.JButton btRelatGeralReg;
    private javax.swing.JButton btSairReg;
    private javax.swing.JButton delReg;
    private javax.swing.JButton insEntradaReg;
    private javax.swing.JLabel rtCliente;
    private javax.swing.JLabel rtIdFunc;
    private javax.swing.JLabel rtVeiculoPlaca;
    // End of variables declaration//GEN-END:variables
}
