//Livia Almeida Rosa
//Tabela só adiciona as informaçoes depois de preencher Cadastro de registro Estacionamento(ultima informaçao)...
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FormRelatorioGeral extends javax.swing.JFrame {

    private static FormRelatorioGeral formRelUnico;
    
    private BDPrincipal bd = BDPrincipal.getBDPrincipal();
    
    private FormRelatorioGeral() {
        initComponents();
    }
    
    //MÉTODO SINGLETON
    public static FormRelatorioGeral getFormRelatorioGeral() {
        if (formRelUnico == null) {
            formRelUnico = new FormRelatorioGeral();
        }
        return formRelUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabGeral = new javax.swing.JTable();
        tituloRegGer = new javax.swing.JLabel();
        btSairRelGeral = new javax.swing.JButton();
        btCadClienRel = new javax.swing.JButton();
        btCadFunRel = new javax.swing.JButton();
        btCadVeRel = new javax.swing.JButton();
        btCadRegRel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TabGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome Cliente", "Nome Fun", "Cpf Cliente", "Cpf Fun", "Entrada", "Saida", "Placa Veiculo", "Gerente", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TabGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabGeralMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabGeral);

        tituloRegGer.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        tituloRegGer.setText("Relatório Geral");

        btSairRelGeral.setText("Sair...");
        btSairRelGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairRelGeralActionPerformed(evt);
            }
        });

        btCadClienRel.setText("Cadastro Cliente");
        btCadClienRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadClienRelActionPerformed(evt);
            }
        });

        btCadFunRel.setText("Cadastro Funcionario");
        btCadFunRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadFunRelActionPerformed(evt);
            }
        });

        btCadVeRel.setText("Cadastro Veiculo");
        btCadVeRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadVeRelActionPerformed(evt);
            }
        });

        btCadRegRel.setText("Registrar Estacionamento");
        btCadRegRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadRegRelActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastro Gerente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadClienRel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadFunRel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadVeRel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadRegRel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btSairRelGeral)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tituloRegGer)
                .addGap(322, 322, 322))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tituloRegGer, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadClienRel)
                    .addComponent(btCadFunRel)
                    .addComponent(btCadVeRel)
                    .addComponent(btCadRegRel)
                    .addComponent(btSairRelGeral)
                    .addComponent(jButton1))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabGeralMouseClicked
        selecionarTabela();
    }//GEN-LAST:event_TabGeralMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        montarTabela();
    }//GEN-LAST:event_formWindowActivated

    private void btSairRelGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairRelGeralActionPerformed
        sairFormulario();
    }//GEN-LAST:event_btSairRelGeralActionPerformed

    private void btCadClienRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadClienRelActionPerformed
        FormCadastroCliente.getFormCadastroCliente().setVisible(true);
    }//GEN-LAST:event_btCadClienRelActionPerformed

    private void btCadFunRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadFunRelActionPerformed
        FormCadFuncionario.getFormCadFuncionario().setVisible(true);
    }//GEN-LAST:event_btCadFunRelActionPerformed

    private void btCadVeRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadVeRelActionPerformed
         FormCadVeiculo.getFormCadVeiculoUnico().setVisible(true);
    }//GEN-LAST:event_btCadVeRelActionPerformed

    private void btCadRegRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadRegRelActionPerformed
        FormCadRegEst.getFormCadRegEst().setVisible(true);
    }//GEN-LAST:event_btCadRegRelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormCadGerente.getFormCadGerente().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
public void montarTabela(){
    
    DefaultTableModel tabModel = (DefaultTableModel)TabGeral.getModel(); 
    
    int posLin = 0;
    tabModel.setRowCount(posLin); 
    
    Gerente gBusca = new Gerente();
    
    for(RegistroEstacionamento reg : bd.getBdRegistros()){
       
        
        String status = (reg.getHoraSaida() != null) ? "FINALIZADO" : "ATIVO";
        double valor = reg.calcularValor();
        
        gBusca.setCpf(reg.getFuncionario().getCpf());
        Gerente gerenteEncontrado = bd.consGerenteCpf(gBusca);
        
        String infoFuncao = (gerenteEncontrado != null) 
                            ? "GERENTE (" + gerenteEncontrado.getSetor() + ")" // Se encontrou, exibe Setor
                            : "Operador Comum";
        
        tabModel.insertRow(posLin, new Object[]{
            reg.getCliente().getNome(),
            reg.getFuncionario().getNome(),
            reg.getCliente().getCpf(),
            reg.getFuncionario().getCpf(),
            reg.getHoraEntrada().toString().substring(0, 16),
           (reg.getHoraSaida() != null ? reg.getHoraSaida().toString().substring(0, 16) : "EM ABERTO"),
            reg.getVeiculo().getPlaca(),
            infoFuncao,
            String.format("%.2f", valor)
        });
        posLin++;
    }
}


public void selecionarTabela(){
        String valLin = "";
        int posLin = TabGeral.getSelectedRow();
        
        for(int col = 0; col < TabGeral.getColumnCount(); col++ ){
            valLin += TabGeral.getModel().getValueAt(posLin,col).toString();
            
            if(col+1 < TabGeral.getColumnCount()){
                valLin += " - ";
            }
        }
                JOptionPane.showMessageDialog(
                null,
                "Valor da Linha: "+valLin,
                "Seleção em Tabela",
                1
        );
    }

public void sairFormulario(){
    int resp = JOptionPane.showConfirmDialog(
        this,	
        "Realmente deseja sair?",
        "Confirmação de Saída",
        JOptionPane.YES_NO_OPTION
    );
    
    if(resp == 0){	
        dispose();	
    }
}
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabGeral;
    private javax.swing.JButton btCadClienRel;
    private javax.swing.JButton btCadFunRel;
    private javax.swing.JButton btCadRegRel;
    private javax.swing.JButton btCadVeRel;
    private javax.swing.JButton btSairRelGeral;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel tituloRegGer;
    // End of variables declaration//GEN-END:variables
}
