//Livia Almeida Rosa
import javax.swing.JOptionPane;

public class FormCadastroCliente extends javax.swing.JFrame {
    
    private static FormCadastroCliente formCadClienteUnico;
    
    private BDPrincipal bd = BDPrincipal.getBDPrincipal();
    private Cliente clienteTemp = new Cliente();
   
    private FormCadastroCliente() {
        initComponents();
    }
    
//MÉTODO SINGLETON
public static FormCadastroCliente getFormCadastroCliente(){
    if(formCadClienteUnico == null){
        formCadClienteUnico = new FormCadastroCliente();
    } 
    
    return formCadClienteUnico; 

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextNome = new javax.swing.JTextField();
        TextCpf = new javax.swing.JTextField();
        TextId = new javax.swing.JTextField();
        textRg = new javax.swing.JTextField();
        InserirCliente = new javax.swing.JButton();
        btAltCpfCli = new javax.swing.JButton();
        btDeletCpfCli = new javax.swing.JButton();
        btConCpfCli = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        rtNome = new javax.swing.JLabel();
        rtCpf = new javax.swing.JLabel();
        rtId = new javax.swing.JLabel();
        rtRg = new javax.swing.JLabel();
        tituloCliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TextNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextNomeMouseClicked(evt);
            }
        });
        TextNome.addActionListener(this::TextNomeActionPerformed);

        TextId.addActionListener(this::TextIdActionPerformed);

        InserirCliente.setText("Inserir");
        InserirCliente.addActionListener(this::InserirClienteActionPerformed);

        btAltCpfCli.setText("Alterar");
        btAltCpfCli.addActionListener(this::btAltCpfCliActionPerformed);

        btDeletCpfCli.setText("Deletar ");
        btDeletCpfCli.addActionListener(this::btDeletCpfCliActionPerformed);

        btConCpfCli.setText("Consultar Cpf");
        btConCpfCli.addActionListener(this::btConCpfCliActionPerformed);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(this::btLimparActionPerformed);

        btSair.setText("Sair");
        btSair.addActionListener(this::btSairActionPerformed);

        rtNome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtNome.setText("NOME");

        rtCpf.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtCpf.setText("CPF");

        rtId.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtId.setText("ID");

        rtRg.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtRg.setText("RG");

        tituloCliente.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        tituloCliente.setText("Cadastro Cliente");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rtNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rtId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rtRg)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                                    .addComponent(TextCpf, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TextNome, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btLimpar)
                                .addGap(18, 18, 18)
                                .addComponent(btSair)
                                .addGap(19, 19, 19))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textRg, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InserirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAltCpfCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btDeletCpfCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btConCpfCli)
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rtCpf)
                    .addComponent(TextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtRg))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InserirCliente)
                    .addComponent(btAltCpfCli)
                    .addComponent(btDeletCpfCli)
                    .addComponent(btConCpfCli))
                .addGap(18, 18, 18)
                .addComponent(tituloCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar)
                    .addComponent(btSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeActionPerformed

    private void InserirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InserirClienteActionPerformed
       insCliente();
    }//GEN-LAST:event_InserirClienteActionPerformed

    private void btAltCpfCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltCpfCliActionPerformed
        altClienteCpf();
    }//GEN-LAST:event_btAltCpfCliActionPerformed

    private void btConCpfCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConCpfCliActionPerformed
        consClienteCpf();
    }//GEN-LAST:event_btConCpfCliActionPerformed

    private void btDeletCpfCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeletCpfCliActionPerformed
        apagClienteCpf();
    }//GEN-LAST:event_btDeletCpfCliActionPerformed

    private void TextNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextNomeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeMouseClicked

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sairFormulario();
    }//GEN-LAST:event_btSairActionPerformed

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

private void limparCampos() {
    TextCpf.setText("");
    TextNome.setText("");
    TextId.setText("");
    textRg.setText("");
    TextCpf.requestFocus();
    }

    public void apagClienteCpf(){
        Cliente clienteTemp = new Cliente();
        clienteTemp.setCpf(Integer.parseInt(TextCpf.getText()));
        
        clienteTemp = bd.delClienteCpf(clienteTemp);
        
        if(clienteTemp == null){
            JOptionPane.showMessageDialog(
                null,
                "Cliente deletado com sucesso!",
                "Deleção de Cliente",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Cliente com este CPF!",
                "Deleção de Cliente",
                JOptionPane.ERROR_MESSAGE
        );
        TextCpf.setText("");
        TextCpf.requestFocus();
        }
    }
    
    public void altClienteCpf(){
        Cliente clienteTemp = new Cliente();
         clienteTemp.setCpf(Integer.parseInt(TextCpf.getText()));
        
        clienteTemp = bd.atualizaClienteCpf(clienteTemp);
        
        if(clienteTemp != null){
            
            TextCpf.setText(Integer.toString(clienteTemp.getCpf()));
            TextNome.setText(clienteTemp.getNome());
            textRg.setText(String.valueOf(clienteTemp.getRg()));
            TextId.setText(String.valueOf(clienteTemp.getIdCliente()));
            
            JOptionPane.showMessageDialog(
                null,
                "Cliente atualizado com sucesso! Confira os dados",
                "Alteração de Cliente",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Cliente com este CPF!",
                "Alteração de Cliente",
                JOptionPane.ERROR_MESSAGE
        );
        TextCpf.setText("");
        TextCpf.requestFocus();
        }
    }
    
    public void consClienteCpf(){
        Cliente clienteTemp = new Cliente();
        clienteTemp.setCpf(Integer.parseInt(TextCpf.getText()));

        clienteTemp = bd.consClienteCpf(clienteTemp);
        
        if(clienteTemp != null){
            TextCpf.setText(Integer.toString(clienteTemp.getCpf()));
            TextNome.setText(clienteTemp.getNome());
            textRg.setText(String.valueOf(clienteTemp.getRg()));
            TextId.setText(String.valueOf(clienteTemp.getIdCliente()));
            JOptionPane.showMessageDialog(
                null,
                "Cliente encontrado com sucesso! Confira os dados",
                "Consulta de Cliente",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Cliente com este CPF!",
                "Consulta de Cliente",
                JOptionPane.ERROR_MESSAGE
        );
        TextCpf.setText("");
        TextCpf.requestFocus();
        }
    }
    
    public void insCliente(){
         Cliente clienteTemp = new Cliente();
        try{
            clienteTemp.setCpf(Integer.parseInt(TextCpf.getText()));
            clienteTemp.setNome(TextNome.getText());
            clienteTemp.setRg(Integer.parseInt(textRg.getText()));
            clienteTemp.setIdCliente(Integer.parseInt(TextId.getText()));

            clienteTemp = bd.insCliente(clienteTemp);

            if(clienteTemp != null){
                JOptionPane.showMessageDialog(
                    null,
                    "Cliente inserido com sucesso!",
                    "Inserção de Cliente",
                    JOptionPane.INFORMATION_MESSAGE
                );
                limparCampos();
            }
            else{
                JOptionPane.showMessageDialog(
                    null,
                    "Já existe um Cliente com este Cpf!",
                    "Inserção de Cliente",
                    JOptionPane.ERROR_MESSAGE
                );
                TextCpf.setText("");
                TextCpf.requestFocus();
            }
        }
        catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(
                null,
                "O CPF deve ser um número inteiro",
                "Erro de CPF",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf.setText("");
            TextCpf.requestFocus();  
        }
        
    }

public void sairFormulario(){
    int resp = JOptionPane.showConfirmDialog(
        null, 
        "Realmente deseja sair?",
        "Confirmação de Saída",
        JOptionPane.YES_NO_OPTION
    );
   
    if(resp == 0){ 
        dispose(); 
    }
}


    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InserirCliente;
    private javax.swing.JTextField TextCpf;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextNome;
    private javax.swing.JButton btAltCpfCli;
    private javax.swing.JButton btConCpfCli;
    private javax.swing.JButton btDeletCpfCli;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtRg;
    private javax.swing.JTextField textRg;
    private javax.swing.JLabel tituloCliente;
    // End of variables declaration//GEN-END:variables
}
