//Livia Almeida Rosa
import javax.swing.JOptionPane;


public class FormCadFuncionario extends javax.swing.JFrame {

   
    private static FormCadFuncionario formCadFuncionarioUnico;
    
     private BDPrincipal bd = BDPrincipal.getBDPrincipal();
    private Funcionario FuncionarioTemp = new Funcionario();
    
    private FormCadFuncionario() {
        initComponents();
    }

    //MÉTODO SINGLETON
public static FormCadFuncionario getFormCadFuncionario (){
    if(formCadFuncionarioUnico == null){
        formCadFuncionarioUnico = new FormCadFuncionario();
    } 
    
    return formCadFuncionarioUnico; 

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtNome = new javax.swing.JLabel();
        rtCpf = new javax.swing.JLabel();
        rtId = new javax.swing.JLabel();
        rtSalario = new javax.swing.JLabel();
        TextNome2 = new javax.swing.JTextField();
        TextCpf2 = new javax.swing.JTextField();
        TextId2 = new javax.swing.JTextField();
        TextSalario2 = new javax.swing.JTextField();
        btInsFunc = new javax.swing.JButton();
        btAltFunc = new javax.swing.JButton();
        btDeleFunc = new javax.swing.JButton();
        btConsFunc = new javax.swing.JButton();
        btLimparFunc = new javax.swing.JButton();
        btSairFunc = new javax.swing.JButton();
        TituloFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtNome.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtNome.setText("NOME");

        rtCpf.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtCpf.setText("CPF");

        rtId.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtId.setText("ID");

        rtSalario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        rtSalario.setText("SALARIO");

        btInsFunc.setText("Inserir");
        btInsFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsFuncActionPerformed(evt);
            }
        });

        btAltFunc.setText("Alterar");
        btAltFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltFuncActionPerformed(evt);
            }
        });

        btDeleFunc.setText("Deletar");
        btDeleFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDeleFuncActionPerformed(evt);
            }
        });

        btConsFunc.setText("Consultar Cpf");
        btConsFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsFuncActionPerformed(evt);
            }
        });

        btLimparFunc.setText("Limpar");
        btLimparFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparFuncActionPerformed(evt);
            }
        });

        btSairFunc.setText("Sair");
        btSairFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairFuncActionPerformed(evt);
            }
        });

        TituloFuncionario.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        TituloFuncionario.setText("Cadastro Funcionario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btLimparFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSairFunc)
                .addGap(11, 11, 11))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rtNome)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(rtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rtCpf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextNome2)
                                    .addComponent(TextId2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                    .addComponent(TextCpf2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rtSalario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TituloFuncionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btInsFunc)
                                .addGap(18, 18, 18)
                                .addComponent(btAltFunc)
                                .addGap(18, 18, 18)
                                .addComponent(btDeleFunc)))
                        .addGap(18, 18, 18)
                        .addComponent(btConsFunc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(TextNome2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(TextCpf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtId)
                    .addComponent(TextId2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtSalario)
                    .addComponent(TextSalario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsFunc)
                    .addComponent(btAltFunc)
                    .addComponent(btDeleFunc)
                    .addComponent(btConsFunc))
                .addGap(18, 18, 18)
                .addComponent(TituloFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimparFunc)
                    .addComponent(btSairFunc))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsFuncActionPerformed
        insFuncionario();
    }//GEN-LAST:event_btInsFuncActionPerformed

    private void btAltFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltFuncActionPerformed
        altFuncionarioCpf();
    }//GEN-LAST:event_btAltFuncActionPerformed

    private void btDeleFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDeleFuncActionPerformed
        apagFuncionarioCpf();
    }//GEN-LAST:event_btDeleFuncActionPerformed

    private void btConsFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsFuncActionPerformed
        consFuncionarioCpf();
    }//GEN-LAST:event_btConsFuncActionPerformed

    private void btLimparFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparFuncActionPerformed
       limparCampos();
    }//GEN-LAST:event_btLimparFuncActionPerformed

    private void btSairFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairFuncActionPerformed
       sairFormulario();
    }//GEN-LAST:event_btSairFuncActionPerformed
private void limparCampos() {
    TextCpf2.setText("");
    TextNome2.setText(""); 
    TextSalario2.setText(""); 
    TextId2.setText(""); 
    TextCpf2.requestFocus();
}

public void apagFuncionarioCpf(){
    Funcionario funcionarioTemp = new Funcionario();
        funcionarioTemp.setCpf(Integer.parseInt(TextCpf2.getText())); 
        
        Funcionario funcTemp = bd.delFuncionarioCpf(funcionarioTemp);
        
        if(funcTemp == null){ 
            JOptionPane.showMessageDialog(
                null,
                "Funcionário deletado com sucesso!",
                "Deleção de Funcionário",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{ 
            JOptionPane.showMessageDialog(
                null,
                "Não existe Funcionário com este CPF!",
                "Deleção de Funcionário",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf2.setText("");
            TextCpf2.requestFocus();
        }
    } 


public void altFuncionarioCpf(){
    Funcionario funcionarioTemp = new Funcionario();
        funcionarioTemp.setCpf(Integer.parseInt(TextCpf2.getText()));
        
        funcionarioTemp = bd.atualizaFuncionarioCpf(funcionarioTemp);
        
        if(funcionarioTemp != null){
            TextCpf2.setText(Integer.toString(funcionarioTemp.getCpf()));
            TextNome2.setText(funcionarioTemp.getNome());
            
            JOptionPane.showMessageDialog(
                null,
                "Funcionário atualizado com sucesso! Confira os dados",
                "Alteração de Funcionário",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Funcionário com este CPF!",
                "Alteração de Funcionário",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf2.setText("");
            TextCpf2.requestFocus();
        }
    } 

public void consFuncionarioCpf(){
    Funcionario funcionarioTemp = new Funcionario();
        funcionarioTemp.setCpf(Integer.parseInt(TextCpf2.getText()));
        funcionarioTemp = bd.consFuncionarioCpf(funcionarioTemp);
        
        if(funcionarioTemp != null){
            TextCpf2.setText(Integer.toString(funcionarioTemp.getCpf()));
            TextNome2.setText(funcionarioTemp.getNome());
            TextSalario2.setText(String.valueOf(funcionarioTemp.getSalario())); // Salário é double
            TextId2.setText(String.valueOf(funcionarioTemp.getIdFuncionario())); // ID é int
            
            JOptionPane.showMessageDialog(
                null,
                "Funcionário encontrado com sucesso! Confira os dados",
                "Consulta de Funcionário",
                JOptionPane.INFORMATION_MESSAGE
            );
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Não existe Funcionário com este CPF!",
                "Consulta de Funcionário",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf2.setText("");
            TextCpf2.requestFocus();
        }
}

public void insFuncionario(){
    Funcionario funcionarioTemp = new Funcionario();
    try{
        funcionarioTemp.setCpf(Integer.parseInt(TextCpf2.getText()));
        funcionarioTemp.setNome(TextNome2.getText());
        funcionarioTemp.setSalario(Double.parseDouble(TextSalario2.getText().trim()));
        funcionarioTemp.setIdFuncionario(Integer.parseInt(TextId2.getText().trim()));

        funcionarioTemp = bd.insFuncionario(funcionarioTemp);
        
        if(funcionarioTemp != null){
            JOptionPane.showMessageDialog(
                null,
                "Funcionário inserido com sucesso!",
                "Inserção de Funcionário",
                JOptionPane.INFORMATION_MESSAGE
            );
            limparCampos();
        }
        else{
            JOptionPane.showMessageDialog(
                null,
                "Já existe um Funcionário com este Cpf!",
                "Inserção de Funcionário",
                JOptionPane.ERROR_MESSAGE
            );
            TextCpf2.setText("");
            TextCpf2.requestFocus();
        }
    }
    catch(NumberFormatException nfe){
        JOptionPane.showMessageDialog(
            null,
            "O CPF, Salário e ID devem ser números válidos",
            "Erro de Formato",
            JOptionPane.ERROR_MESSAGE
        );
        TextCpf2.setText("");
        TextCpf2.requestFocus();	
    }
}
public void sairFormulario(){
    int resp = JOptionPane.showConfirmDialog(
        null, 
        "Realmente deseja sair?",
        "Confirmação de Saída",
        JOptionPane.YES_NO_OPTION
    );
   
    if(resp == 0){ 
        dispose(); 
    }
}

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextCpf2;
    private javax.swing.JTextField TextId2;
    private javax.swing.JTextField TextNome2;
    private javax.swing.JTextField TextSalario2;
    private javax.swing.JLabel TituloFuncionario;
    private javax.swing.JButton btAltFunc;
    private javax.swing.JButton btConsFunc;
    private javax.swing.JButton btDeleFunc;
    private javax.swing.JButton btInsFunc;
    private javax.swing.JButton btLimparFunc;
    private javax.swing.JButton btSairFunc;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtId;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSalario;
    // End of variables declaration//GEN-END:variables
}
